return function(c)
  return {
    Normal = { fg = c.fg, bg = c.bg },
    NormalNC = { fg = c.fg, bg = c.bg },
    NormalFloat = { fg = c.fg, bg = c.bg_alt },
    FloatBorder = { fg = c.border, bg = c.bg_alt },
    FloatTitle = { fg = c.blue, bg = c.bg_alt, bold = true },
    ColorColumn = { bg = c.bg_alt },
    Conceal = { fg = c.subtle },
    Cursor = { fg = c.bg, bg = c.fg_bright },
    CursorColumn = { bg = c.bg_alt },
    CursorLine = { bg = c.bg_alt },
    CursorLineNr = { fg = c.blue, bg = c.bg_alt, bold = true },
    LineNr = { fg = c.subtle },
    LineNrAbove = { fg = c.subtle },
    LineNrBelow = { fg = c.subtle },
    Directory = { fg = c.blue },
    EndOfBuffer = { fg = c.bg },
    FoldColumn = { fg = c.subtle, bg = c.bg },
    Folded = { fg = c.muted, bg = c.bg_alt },
    MatchParen = { fg = c.blue_soft, bg = c.blue_bg, bold = true },
    NonText = { fg = c.subtle },
    SpecialKey = { fg = c.subtle },
    Whitespace = { fg = c.subtle },
    SignColumn = { fg = c.muted, bg = c.bg },
    WinSeparator = { fg = c.border },
    VertSplit = { link = 'WinSeparator' },
    Visual = { bg = c.blue_bg },
    VisualNOS = { bg = c.bg_highlight },
    Search = { fg = c.bg, bg = c.yellow },
    IncSearch = { fg = c.bg, bg = c.blue_soft, bold = true },
    CurSearch = { link = 'IncSearch' },
    Substitute = { fg = c.bg, bg = c.red },
    QuickFixLine = { bg = c.blue_bg, bold = true },
    Question = { fg = c.blue },
    Title = { fg = c.fg_bright, bold = true },
    ErrorMsg = { fg = c.red, bold = true },
    WarningMsg = { fg = c.yellow },
    MoreMsg = { fg = c.blue },
    ModeMsg = { fg = c.fg_bright, bold = true },
    MsgArea = { fg = c.fg },
    MsgSeparator = { fg = c.border },

    StatusLine = { fg = c.fg, bg = c.bg_soft },
    StatusLineNC = { fg = c.muted, bg = c.bg_alt },
    TabLine = { fg = c.muted, bg = c.bg_alt },
    TabLineFill = { bg = c.bg_alt },
    TabLineSel = { fg = c.fg_bright, bg = c.bg, bold = true },
    WinBar = { fg = c.fg, bg = c.bg },
    WinBarNC = { fg = c.muted, bg = c.bg },

    Pmenu = { fg = c.fg, bg = c.bg_soft },
    PmenuSel = { fg = c.fg_bright, bg = c.blue_bg, bold = true },
    PmenuKind = { fg = c.blue, bg = c.bg_soft },
    PmenuKindSel = { fg = c.blue_soft, bg = c.blue_bg },
    PmenuExtra = { fg = c.muted, bg = c.bg_soft },
    PmenuExtraSel = { fg = c.muted, bg = c.blue_bg },
    PmenuSbar = { bg = c.bg_highlight },
    PmenuThumb = { bg = c.subtle },
    WildMenu = { fg = c.fg_bright, bg = c.blue_bg },

    DiffAdd = { fg = c.green, bg = c.bg_alt },
    DiffChange = { fg = c.yellow, bg = c.bg_alt },
    DiffDelete = { fg = c.red, bg = c.bg_alt },
    DiffText = { fg = c.blue_soft, bg = c.blue_bg, bold = true },
    Added = { fg = c.green },
    Changed = { fg = c.yellow },
    Removed = { fg = c.red },

    SpellBad = { sp = c.red, undercurl = true },
    SpellCap = { sp = c.blue, undercurl = true },
    SpellLocal = { sp = c.green, undercurl = true },
    SpellRare = { sp = c.purple, undercurl = true },
  }
end
