return function(c)
  return {
    Comment = { fg = c.muted, italic = true },
    Constant = { fg = c.yellow },
    String = { fg = c.green },
    Character = { fg = c.green },
    Number = { fg = c.orange },
    Boolean = { fg = c.orange },
    Float = { fg = c.orange },
    Identifier = { fg = c.fg },
    Function = { fg = c.blue_soft },
    Statement = { fg = c.purple },
    Conditional = { fg = c.purple },
    Repeat = { fg = c.purple },
    Label = { fg = c.blue },
    Operator = { fg = c.fg },
    Keyword = { fg = c.purple },
    Exception = { fg = c.red },
    PreProc = { fg = c.blue },
    Include = { fg = c.purple },
    Define = { fg = c.purple },
    Macro = { fg = c.blue },
    PreCondit = { fg = c.purple },
    Type = { fg = c.blue },
    StorageClass = { fg = c.purple },
    Structure = { fg = c.blue },
    Typedef = { fg = c.blue },
    Special = { fg = c.blue },
    SpecialChar = { fg = c.orange },
    Tag = { fg = c.blue },
    Delimiter = { fg = c.muted },
    SpecialComment = { fg = c.muted, bold = true },
    Debug = { fg = c.red },
    Underlined = { fg = c.blue, underline = true },
    Ignore = { fg = c.subtle },
    Error = { fg = c.red },
    Todo = { fg = c.blue, bg = c.blue_bg, bold = true },

    markdownH1 = { fg = c.fg_bright, bold = true },
    markdownH2 = { fg = c.fg_bright, bold = true },
    markdownH3 = { fg = c.fg_bright, bold = true },
    markdownHeadingDelimiter = { fg = c.blue },
    markdownCode = { fg = c.green },
    markdownCodeBlock = { fg = c.green },
    markdownLinkText = { fg = c.blue },
    markdownUrl = { fg = c.muted, underline = true },
    helpHyperTextJump = { fg = c.blue, underline = true },
    helpCommand = { fg = c.green },
  }
end
