return function(c)
  return {
    ['@variable'] = { fg = c.fg },
    ['@variable.builtin'] = { fg = c.blue },
    ['@variable.parameter'] = { fg = c.fg },
    ['@variable.member'] = { fg = c.fg },
    ['@constant'] = { link = 'Constant' },
    ['@constant.builtin'] = { fg = c.orange },
    ['@module'] = { fg = c.blue },
    ['@label'] = { link = 'Label' },
    ['@string'] = { link = 'String' },
    ['@string.escape'] = { fg = c.orange },
    ['@string.regexp'] = { fg = c.green },
    ['@character'] = { link = 'Character' },
    ['@boolean'] = { link = 'Boolean' },
    ['@number'] = { link = 'Number' },
    ['@type'] = { link = 'Type' },
    ['@type.builtin'] = { fg = c.blue },
    ['@attribute'] = { fg = c.blue },
    ['@property'] = { fg = c.fg },
    ['@function'] = { link = 'Function' },
    ['@function.builtin'] = { fg = c.blue_soft },
    ['@function.call'] = { fg = c.blue_soft },
    ['@function.method'] = { fg = c.blue_soft },
    ['@function.method.call'] = { fg = c.blue_soft },
    ['@constructor'] = { fg = c.blue },
    ['@operator'] = { link = 'Operator' },
    ['@keyword'] = { link = 'Keyword' },
    ['@keyword.function'] = { fg = c.purple },
    ['@keyword.return'] = { fg = c.purple },
    ['@keyword.import'] = { fg = c.purple },
    ['@keyword.exception'] = { fg = c.red },
    ['@punctuation.delimiter'] = { fg = c.muted },
    ['@punctuation.bracket'] = { fg = c.muted },
    ['@punctuation.special'] = { fg = c.blue },
    ['@comment'] = { link = 'Comment' },
    ['@comment.error'] = { fg = c.red, bold = true },
    ['@comment.warning'] = { fg = c.yellow, bold = true },
    ['@comment.todo'] = { fg = c.blue, bg = c.blue_bg, bold = true },
    ['@markup.heading'] = { fg = c.fg_bright, bold = true },
    ['@markup.heading.1'] = { fg = c.fg_bright, bold = true },
    ['@markup.heading.2'] = { fg = c.fg_bright, bold = true },
    ['@markup.strong'] = { bold = true },
    ['@markup.italic'] = { italic = true },
    ['@markup.strikethrough'] = { strikethrough = true },
    ['@markup.link'] = { fg = c.blue },
    ['@markup.link.url'] = { fg = c.muted, underline = true },
    ['@markup.raw'] = { fg = c.green },
    ['@markup.list'] = { fg = c.blue },
    ['@diff.plus'] = { fg = c.green },
    ['@diff.minus'] = { fg = c.red },
    ['@diff.delta'] = { fg = c.yellow },
  }
end
