return function(c)
  return {
    CmpItemAbbr = { fg = c.fg },
    CmpItemAbbrDeprecated = { fg = c.subtle, strikethrough = true },
    CmpItemAbbrMatch = { fg = c.blue_soft, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.blue },
    CmpItemMenu = { fg = c.muted, italic = true },
    CmpItemKindDefault = { fg = c.muted },
    CmpItemKindText = { fg = c.fg },
    CmpItemKindMethod = { fg = c.blue_soft },
    CmpItemKindFunction = { fg = c.blue_soft },
    CmpItemKindConstructor = { fg = c.blue },
    CmpItemKindField = { fg = c.fg },
    CmpItemKindVariable = { fg = c.fg },
    CmpItemKindClass = { fg = c.blue },
    CmpItemKindInterface = { fg = c.blue },
    CmpItemKindModule = { fg = c.blue },
    CmpItemKindProperty = { fg = c.fg },
    CmpItemKindUnit = { fg = c.orange },
    CmpItemKindValue = { fg = c.orange },
    CmpItemKindEnum = { fg = c.blue },
    CmpItemKindKeyword = { fg = c.purple },
    CmpItemKindSnippet = { fg = c.green },
    CmpItemKindColor = { fg = c.yellow },
    CmpItemKindFile = { fg = c.fg },
    CmpItemKindReference = { fg = c.blue },
    CmpItemKindFolder = { fg = c.blue },
    CmpItemKindEnumMember = { fg = c.orange },
    CmpItemKindConstant = { fg = c.yellow },
    CmpItemKindStruct = { fg = c.blue },
    CmpItemKindEvent = { fg = c.purple },
    CmpItemKindOperator = { fg = c.fg },
    CmpItemKindTypeParameter = { fg = c.blue },
  }
end
