return function(c)
  return {
    WhichKey = { fg = c.blue },
    WhichKeyGroup = { fg = c.blue_soft },
    WhichKeyDesc = { fg = c.fg },
    WhichKeySeparator = { fg = c.subtle },
    WhichKeyFloat = { bg = c.bg_alt },
    TroubleNormal = { fg = c.fg, bg = c.bg_alt },
    TroubleNormalNC = { fg = c.fg, bg = c.bg_alt },
    TroubleCount = { fg = c.blue, bg = c.blue_bg },
    TroubleText = { fg = c.fg },
    NotifyERRORBorder = { fg = c.red },
    NotifyWARNBorder = { fg = c.yellow },
    NotifyINFOBorder = { fg = c.blue },
    NotifyDEBUGBorder = { fg = c.muted },
    NotifyTRACEBorder = { fg = c.purple },
    NotifyERRORIcon = { fg = c.red },
    NotifyWARNIcon = { fg = c.yellow },
    NotifyINFOIcon = { fg = c.blue },
    NotifyDEBUGIcon = { fg = c.muted },
    NotifyTRACEIcon = { fg = c.purple },
    NoiceCmdlineIcon = { fg = c.blue },
    NoiceCmdlinePopupBorder = { fg = c.blue },
    NoiceConfirmBorder = { fg = c.blue },
    DapBreakpoint = { fg = c.red },
    DapBreakpointCondition = { fg = c.yellow },
    DapLogPoint = { fg = c.blue },
    DapStopped = { fg = c.green },
    DapUIVariable = { fg = c.fg },
    DapUIScope = { fg = c.blue },
    DapUIType = { fg = c.blue },
    DapUIValue = { fg = c.fg },
    DapUIModifiedValue = { fg = c.yellow, bold = true },
    DapUIDecoration = { fg = c.blue },
    BufferLineFill = { bg = c.bg_alt },
    BufferLineBackground = { fg = c.muted, bg = c.bg_alt },
    BufferLineBufferSelected = { fg = c.fg_bright, bg = c.bg, bold = true },
    BufferLineIndicatorSelected = { fg = c.blue, bg = c.bg },
    IblIndent = { fg = c.border },
    IblScope = { fg = c.subtle },
    TreesitterContext = { bg = c.bg_alt },
    TreesitterContextLineNumber = { fg = c.muted, bg = c.bg_alt },
    OilDir = { fg = c.blue },
    OilDirIcon = { fg = c.blue },
    OilLink = { fg = c.blue_soft },
    OilHidden = { fg = c.subtle },
    FlashLabel = { fg = c.bg, bg = c.blue, bold = true },
    FlashMatch = { fg = c.blue_soft, bold = true },
    FlashCurrent = { fg = c.bg, bg = c.purple, bold = true },
    LeapMatch = { fg = c.blue_soft, bold = true },
    LeapLabelPrimary = { fg = c.bg, bg = c.blue, bold = true },
    AlphaHeader = { fg = c.blue },
    AlphaButtons = { fg = c.fg },
    AlphaShortcut = { fg = c.blue_soft },
    AlphaFooter = { fg = c.muted, italic = true },
  }
end
